### PR TITLE
Port plugin to executeShellCommand from runCommand

### LINKED ISSUE #3: runCommand is deprecated
The deprecated `runCommand` was removed in [Backstage Scaffolder Backend 0.18.0](https://github.com/backstage/backstage/blob/master/plugins/scaffolder-backend/CHANGELOG.md#0180) in favour of `executeShellCommand`. This makes the plugin not compatible with recent versions of Backstage.

### PR DESCRIPTION
**Pull request by patriziobruno**
The deprecated `runCommand` was removed in [Backstage Scaffolder Backend 0.18.0](https://github.com/backstage/backstage/blob/master/plugins/scaffolder-backend/CHANGELOG.md#0180) in favour of `executeShellCommand`.
This patch replaces calls to `runCommand` with calls to `executeShellCommand` and updates dependencies.

Fixes #3

### CODE REVIEW

**Comment by patriziobruno** [comment]
fixes #3

**Comment by patriziobruno** [comment]
fixes #3

**Comment by alefcarlos** [comment]
Hey! Thank you for that contribution !!

**Comment by patriziobruno** [comment]
> Hey! Thank you for that contribution !!

Thank you for accepting it! And there's more coming :smile: 
I need NuGet authentication to install templates from an authenticated source. I've already an implementation working, I just need to iron out some details around security, then I'll submit a new PR.

**Comment by alefcarlos** [comment]
I have this scenario as well, but I only added a nugge.config on backstage root folder with credentials. But it will be good to this plugins handles authentication over private sources!

**Pull request merged**
